---
language: python
cache: pip

addons:
  apt:
    packages:
    - python-pip

install:
  - pip install ansible ansible-lint
  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' >ansible.cfg

script:
  - ansible-lint --nocolor tasks/main.yml

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/